FROM node:16-alpine as builder
# FROM node:16-alpine is the base image for the container. It is a lightweight image of Node.js 16 on Alpine Linux.
WORKDIR /app
# WORKDIR /app sets the working directory for the container to /app.

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . . 

RUN npm run build
# Copy the rest of the application code to the container.

CMD [ "npm", "run", "start" ]

FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html